export const B1_VOCABULARY = [
  // A1/A2 Foundation (Essential for B1 context)
  { word: "De afspraak", translation: "The appointment / agreement", level: "A2", category: "Noun" },
  { word: "Belangrijk", translation: "Important", level: "A2", category: "Adjective" },
  { word: "Begrijpen", translation: "To understand", level: "A2", category: "Verb" },
  { word: "De ervaring", translation: "The experience", level: "B1", category: "Noun" },
  { word: "Voldoende", translation: "Sufficient / Enough", level: "B1", category: "Adjective" },
  { word: "Regelmatig", translation: "Regularly", level: "B1", category: "Adverb" },
  { word: "Ontwikkelen", translation: "To develop", level: "B1", category: "Verb" },
  { word: "De overheid", translation: "The government", level: "B1", category: "Noun" },
  { word: "Beschikbaar", translation: "Available", level: "B1", category: "Adjective" },
  { word: "Verwachten", translation: "To expect", level: "B1", category: "Verb" },
  { word: "Tegenwoordig", translation: "Nowadays", level: "B1", category: "Adverb" },
  { word: "Ondanks", translation: "Despite", level: "B1", category: "Conjunction" },
  { word: "De beslissing", translation: "The decision", level: "B1", category: "Noun" },
  { word: "Vergelijken", translation: "To compare", level: "B1", category: "Verb" },
  { word: "De omgeving", translation: "The environment / surroundings", level: "B1", category: "Noun" },
  { word: "Behalve", translation: "Except / Besides", level: "B1", category: "Conjunction" },
  { word: "Het onderdeel", translation: "The part / component", level: "B1", category: "Noun" },
  { word: "Het resultaat", translation: "The result", level: "B1", category: "Noun" },
  { word: "Het voordeel", translation: "The advantage", level: "B1", category: "Noun" },
  { word: "Het nadeel", translation: "The disadvantage", level: "B1", category: "Noun" },
  { word: "Organiseren", translation: "To organize", level: "B1", category: "Verb" },
  { word: "Vanzelfsprekend", translation: "Self-evident", level: "B1", category: "Adjective" },
  { word: "De invloed", translation: "The influence", level: "B1", category: "Noun" },
  { word: "Verantwoordelijk", translation: "Responsible", level: "B1", category: "Adjective" },
  { word: "De maatschappij", translation: "The society", level: "B1", category: "Noun" },
  { word: "De opleiding", translation: "The education / training", level: "B1", category: "Noun" },
  { word: "De uitdaging", translation: "The challenge", level: "B1", category: "Noun" },
  { word: "De oplossing", translation: "The solution", level: "B1", category: "Noun" },
  { word: "De mening", translation: "The opinion", level: "B1", category: "Noun" },
  { word: "Discussiëren", translation: "To discuss", level: "B1", category: "Verb" },
  { word: "Presenteren", translation: "To present", level: "B1", category: "Verb" },
  { word: "Verbeteren", translation: "To improve", level: "B1", category: "Verb" },
  { word: "Veranderen", translation: "To change", level: "B1", category: "Verb" },
  { word: "De reden", translation: "The reason", level: "B1", category: "Noun" },
  { word: "Namelijk", translation: "Namely / In fact", level: "B1", category: "Adverb" },
  { word: "Inderdaad", translation: "Indeed / Exactly", level: "B1", category: "Adverb" },
  { word: "Misschien", translation: "Maybe", level: "A1", category: "Adverb" },
  { word: "Waarschijnlijk", translation: "Probably", level: "B1", category: "Adverb" },
  { word: "Eventueel", translation: "Possibly", level: "B1", category: "Adverb" },
  { word: "Bovendien", translation: "Moreover", level: "B1", category: "Conjunction" },
  { word: "Daarentegen", translation: "On the other hand", level: "B1", category: "Conjunction" },
  { word: "Tegelijkertijd", translation: "Simultaneously", level: "B1", category: "Adverb" },
  { word: "Overleggen", translation: "To consult / discuss", level: "B1", category: "Verb" },
  { word: "De kans", translation: "The chance / opportunity", level: "B1", category: "Noun" },
  { word: "Het succes", translation: "The success", level: "B1", category: "Noun" },
  { word: "Gezamenlijk", translation: "Jointly / Together", level: "B1", category: "Adjective" },
  { word: "Individueel", translation: "Individually", level: "B1", category: "Adjective" },
  { word: "De ondersteuning", translation: "The support", level: "B1", category: "Noun" },
  { word: "Het beleid", translation: "The policy", level: "B1", category: "Noun" },
  { word: "De samenwerking", translation: "The collaboration", level: "B1", category: "Noun" },
  { word: "Het overleg", translation: "The consultation / meeting", level: "B1", category: "Noun" },
  { word: "Beheren", translation: "To manage", level: "B1", category: "Verb" },
  { word: "De kennis", translation: "The knowledge", level: "B1", category: "Noun" },
  { word: "De vaardigheid", translation: "The skill", level: "B1", category: "Noun" },
  { word: "Effectief", translation: "Effective", level: "B1", category: "Adjective" },
  { word: "Efficiënt", translation: "Efficient", level: "B1", category: "Adjective" },
  { word: "De kwaliteit", translation: "The quality", level: "B1", category: "Noun" },
  { word: "De kwantiteit", translation: "The quantity", level: "B1", category: "Noun" },
  { word: "De hoeveelheid", translation: "The amount", level: "B1", category: "Noun" },
  { word: "Het gedrag", translation: "The behavior", level: "B1", category: "Noun" },
  { word: "De houding", translation: "The attitude / posture", level: "B1", category: "Noun" },
  { word: "Respectvol", translation: "Respectful", level: "B1", category: "Adjective" },
  { word: "Eerlijk", translation: "Honest", level: "A2", category: "Adjective" },
  { word: "Betrouwbaar", translation: "Reliable", level: "B1", category: "Adjective" },
  { word: "De veiligheid", translation: "The safety / security", level: "B1", category: "Noun" },
  { word: "Het gevaar", translation: "The danger", level: "A2", category: "Noun" },
  { word: "Voorkomen", translation: "To prevent / Occur", level: "B1", category: "Verb" },
  { word: "De situatie", translation: "The situation", level: "A2", category: "Noun" },
  { word: "Het probleem", translation: "The problem", level: "A1", category: "Noun" },
  { word: "Bespreken", translation: "To discuss", level: "A2", category: "Verb" },
  { word: "Uitleggen", translation: "To explain", level: "A2", category: "Verb" },
  { word: "Onthouden", translation: "To remember", level: "A2", category: "Verb" },
  { word: "Vergeten", translation: "To forget", level: "A1", category: "Verb" },
  { word: "De herinnering", translation: "The memory", level: "B1", category: "Noun" },
  { word: "De toekomst", translation: "The future", level: "A2", category: "Noun" },
  { word: "Het verleden", translation: "The past", level: "A2", category: "Noun" },
  { word: "Binnenkort", translation: "Soon", level: "A2", category: "Adverb" },
  { word: "Eindelijk", translation: "Finally", level: "A2", category: "Adverb" },
  { word: "Plotseling", translation: "Suddenly", level: "B1", category: "Adverb" },
  { word: "Soms", translation: "Sometimes", level: "A1", category: "Adverb" },
  { word: "Nooit", translation: "Never", level: "A1", category: "Adverb" },
  { word: "Altijd", level: "A1", translation: "Always", category: "Adverb" },
  { word: "Overal", level: "A2", translation: "Everywhere", category: "Adverb" },
  { word: "Nergens", level: "A2", translation: "Nowhere", category: "Adverb" },
  { word: "Iemand", level: "A1", translation: "Someone", category: "Pronoun" },
  { word: "Niemand", level: "A1", translation: "No one", category: "Pronoun" },
  { word: "Iets", level: "A1", translation: "Something", category: "Pronoun" },
  { word: "Niets", level: "A1", translation: "Nothing", category: "Pronoun" },
  { word: "Alles", level: "A1", translation: "Everything", category: "Pronoun" },
  { word: "Iedereen", level: "A1", translation: "Everyone", category: "Pronoun" },
];