export const B1_VOCABULARY = [
  { word: "Ondanks", translation: "Despite", level: "B1", category: "Conjunction" },
  { word: "De beslissing", translation: "The decision", level: "B1", category: "Noun" },
  { word: "Ontwikkelen", translation: "To develop", level: "B1", category: "Verb" },
  { word: "Vanzelfsprekend", translation: "Self-evident / Of course", level: "B1", category: "Adjective" },
  { word: "Het resultaat", translation: "The result", level: "B1", category: "Noun" },
  { word: "Vergelijken", translation: "To compare", level: "B1", category: "Verb" },
  { word: "De omgeving", translation: "The environment / surroundings", level: "B1", category: "Noun" },
  { word: "Behalve", translation: "Except / Besides", level: "B1", category: "Conjunction" },
  { word: "Het onderdeel", translation: "The part / component", level: "B1", category: "Noun" },
  { word: "Regelmatig", translation: "Regularly", level: "B1", category: "Adverb" },
  { word: "De ervaring", translation: "The experience", level: "B1", category: "Noun" },
  { word: "Voldoende", translation: "Sufficient", level: "B1", category: "Adjective" },
  { word: "De invloed", translation: "The influence", level: "B1", category: "Noun" },
  { word: "Verwachten", translation: "To expect", level: "B1", category: "Verb" },
  { word: "Tegenwoordig", translation: "Nowadays", level: "B1", category: "Adverb" },
  { word: "De overheid", translation: "The government", level: "B1", category: "Noun" },
  { word: "Beschikbaar", translation: "Available", level: "B1", category: "Adjective" },
  { word: "Het voordeel", translation: "The advantage", level: "B1", category: "Noun" },
  { word: "Het nadeel", translation: "The disadvantage", level: "B1", category: "Noun" },
  { word: "Organiseren", translation: "To organize", level: "B1", category: "Verb" },
];
